services:
  api:
    build:
      context: .
    container_name: api
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://db:27017/synth-xps
      - JWT_SECRET=secret
      - JWT_EXPIRATION=1d
    depends_on:
      - db
    restart: always

  db:
    image: mongo:latest
    container_name: db
    volumes:
      - db-data:/data/db
    ports:
      - '27017:27017'

volumes:
  db-data:
